name = "copilot-checkin-api"
main = "worker.js"
compatibility_date = "2026-08-01"

[[d1_databases]]
binding = "DB"
database_name = "copilot-checkin"
database_id = "796da529-eaec-4f25-89d0-ec191059cd9c"
